name: Deploy Frontend to EC2 using Docker and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cv_stream_frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/cv_stream_frontend:latest

    
    - name: Deploy frontend to EC2
      run: |
        echo "${{ secrets.EC2_SSH_FRONTEND_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        echo "Deploying to EC2 instance..."
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONTEND_HOST }} << EOF
          cd aws-pipeline
          git pull https://github.com/OussamaBenSlama/aws-pipeline.git

          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/cv_stream_frontend:latest

          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/cv_stream_frontend:latest
        EOF

