name: Deploy to EC2 using Docker and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cv_stream_backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/cv_stream_backend:latest

    
    - name: Deploy backend to EC2
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        echo "Deploying to EC2 instance..."
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd aws-pipeline
          git pull https://github.com/OussamaBenSlama/aws-pipeline.git

          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/cv_stream_backend:latest

          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend --env-file .env -p 8000:8000 --restart always ${{ secrets.DOCKER_USERNAME }}/cv_stream_backend:latest
        EOF

